### ISSUE TITLE
BH messages broken

### ISSUE THREAD

**Issue by yadij** [Hopbox/charcoal-helper#1]
The point of the BH result code is to inform Squid of errors in the helper. They need to be delivered to STDOUT same as the other result codes if that handling is to take effect before the helper dies. Currently it is delivered to STDERR which is simply a pipe to cache.log and does nothing particularly useful.

Also, the message= parameter needs to use double-quotes (eg. BH message="some text" ) when it contains whitespace or special characters. The helper currently does not do that.

**Comment by yadij** [comment]
Forgot to mention that cache.log (STDERR) message may be useful in addition to the BH on STDOUT, but should use the error codes mentioned in issue #2 - in this case different helpers may have different connectivity results so an "ERROR:" prefix on the STDERR message seems appropriate.

**Comment by codemarauder** [comment]
Modified the code to send BH messages to STDOUT and other error messages to STDERR. Here are the logs when helper is not able to connect to the charcoal server:

Received API KEY xxxxxxxxxxx-416c-4edc-9bf2-a81771272a00
Running for Squid Version 3
ERROR: Charcoal Helper can not connect to charcoal server
2017/06/14 19:23:59| WARNING: redirector #Hlpr1 exited
2017/06/14 19:23:59| Too few redirector processes are running (need 1/20)
2017/06/14 19:23:59| Starting new helpers
2017/06/14 19:23:59| helperOpenServers: Starting 1/20 'charcoal-helper.pl' processes
2017/06/14 19:23:59| ERROR: URL rewrite helper returned invalid result code. Wrong helper? {result=Unknown}

But still something seems missing, as there is no BH shown in the cache.log.

**Comment by yadij** [comment]
That output looks correct to me for what the changes were. The STDOUT messages from the helper to Squid are only logged at high debug levels or when unexpected response line comes back (that {result=Unknown} quote). debug_options 84,9 will show the exact text received from the helper in Squid-3, along with many other related details.

It looks like the first helper had its error and logged that. Squid wrote a WARNING when the "die" happened. Then the BH / helper death recovery process kicked in causing Squid to start a new helper and resend the lookup to that one - which responded with an empty line.
