### ISSUE TITLE
Incorrect ARGV handling

### ISSUE THREAD

**Issue by yadij** [Hopbox/charcoal-helper#2]
The size checking of ARGV to detect the required parameter exists is being delivered to STDERR as it should. But the BH code and message= parameters are being used. Those are internal helper protocol codes for use on STDOUT to instruct Squid to retry on another helper - not for serious configuration issues such as this helper startup logic appears to be reporting.

Squid has a defined set of log prefix codes for highlighting serious configuration issues, which can be used on STDERR output from the helper to integrate with other cache.log processing and scanning software. see [http://wiki.squid-cache.org/SquidFaq/SquidLogs#cache.log](http://wiki.squid-cache.org/SquidFaq/SquidLogs#cache.log) for details of these codes.

Since this error occurs as the helper is aborting and not fixing it will shortly result in Squid itself terminating a FATAL log entry seems appropriate.

**Comment by codemarauder** [comment]
commit https://github.com/Hopbox/charcoal-helper/commit/2cd3a0f985c2083046267eee82f6c7df16113113 tries to address this issue.
